# Generated by Django 2.2.4 on 2020-04-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_images_taken',
            field=models.BooleanField(default=False),
        ),
    ]
